# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files # prevents giant files from being committed.
    -   id: check-ast # checks whether files parse as valid python.
    -   id: check-json # checks json files for parseable syntax.
    -   id: check-yaml # checks yaml files for parseable syntax.
    -   id: check-merge-conflict # checks for files that contain merge conflict strings.
    -   id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source.
    -   id: detect-private-key # checks for the existence of private keys.
    -   id: double-quote-string-fixer # replaces double quoted strings with single quoted strings.
    -   id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
    -   id: name-tests-test # verifies that test files are named correctly, e.g.: --pytest (the default): ensure tests match .*_test\.py
    -   id: pretty-format-json # checks that all your JSON files are pretty. "Pretty" here means that keys are sorted and indented.
    -   id: requirements-txt-fixer # sorts entries in requirements.txt.
    -   id: sort-simple-yaml # sorts simple YAML files which consist only of top-level keys, preserving comments and blocks.
    -   id: trailing-whitespace # trims trailing whitespace.
        language_version: python3

-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8 # enforces flake8 style consistency across Python projects.
        language_version: python3
        args: [--max-line-length=150, --max-complexity=10]

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports # This hook reorders imports in python files.

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade # automatically upgrade syntax for newer versions
        args: [--py36-plus]

-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.3.1
    hooks:
    -   id: sqlfluff-lint # lints sql files with `SQLFluff`
        args: [--dialect, "snowflake"]
        additional_dependencies: ['dbt-snowflake', 'sqlfluff-templater-dbt']

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
    -   id: markdownlint # lint .md files - configure in .markdownlint.rb
        args: [-s, .markdownlint.rb]
    -   id: shellcheck # Ensure shell scripts conform to shellcheck
    -   id: shfmt # Check shell style with shfmt

-   repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.69.1  # the version of cfn-lint to use
    hooks:
    -   id: cfn-python-lint # linter for cfn (yaml) templates
        files: path/to/cfn/dir/.*\.(json|yml|yaml)$
