---
general_params:
  env: dev
  data_src:  # mandatory field
  num_records_to_generate:  # mandatory field
db_connection_params:
  snowflake_account: <snowflake_account>.ap-southeast-2
  snowflake_username:  # mandatory field, e.g., jbloggs@email.com
  snowflake_pass:
  snowflake_p8_key:
  snowflake_p8_key_passphrase:
  snowflake_wh:  # mandatory field
  snowflake_role:  # mandatory field
  snowflake_db:  # mandatory field
  snowflake_db_schema:  # mandatory field
data_src_tables:
  DATA_SRC_tables:  # update DATA source with your data source name (TODO: come back to this)
    - table_name: products
      pk: product_id
    - table_name: brands
      pk: brand_id
    - table_name: categories
      pk: category_id
    - table_name: stocks
      pk: product_id
